from app.services.risk_engine import GraphRiskEngine


def test_mule_ring_scores_higher_than_regular_consumer() -> None:
    accounts = [
        {
            "account_id": "A",
            "holder_name": "Regular",
            "vpa": "a@upi",
            "bank_name": "SBI",
            "city": "Delhi",
            "account_type": "consumer",
            "created_at": "2026-01-01T00:00:00",
            "kyc_level": "FULL",
            "device_id": "D1",
            "phone_hash": "P1",
        },
        {
            "account_id": "B",
            "holder_name": "Mule One",
            "vpa": "b@upi",
            "bank_name": "SBI",
            "city": "Delhi",
            "account_type": "mule",
            "created_at": "2026-01-01T00:00:00",
            "kyc_level": "MINIMUM",
            "device_id": "D2",
            "phone_hash": "P2",
        },
        {
            "account_id": "C",
            "holder_name": "Mule Two",
            "vpa": "c@upi",
            "bank_name": "SBI",
            "city": "Delhi",
            "account_type": "mule",
            "created_at": "2026-01-01T00:00:00",
            "kyc_level": "MINIMUM",
            "device_id": "D2",
            "phone_hash": "P3",
        },
        {
            "account_id": "D",
            "holder_name": "Mule Three",
            "vpa": "d@upi",
            "bank_name": "SBI",
            "city": "Delhi",
            "account_type": "mule",
            "created_at": "2026-01-01T00:00:00",
            "kyc_level": "MINIMUM",
            "device_id": "D2",
            "phone_hash": "P4",
        },
    ]
    transactions = [
        {
            "txn_id": "T1",
            "sender_id": "A",
            "receiver_id": "B",
            "amount": 800,
            "txn_time": "2026-05-01T09:00:00",
            "txn_type": "P2P",
            "channel": "UPI_APP",
            "city": "Delhi",
            "device_id": "D1",
            "status": "SUCCESS",
            "note": "normal",
            "label": "legit",
        },
        {
            "txn_id": "T2",
            "sender_id": "B",
            "receiver_id": "C",
            "amount": 7800,
            "txn_time": "2026-05-01T09:02:00",
            "txn_type": "P2P",
            "channel": "PAYMENT_LINK",
            "city": "Noida",
            "device_id": "D2",
            "status": "SUCCESS",
            "note": "layering",
            "label": "fraud",
        },
        {
            "txn_id": "T3",
            "sender_id": "C",
            "receiver_id": "D",
            "amount": 7600,
            "txn_time": "2026-05-01T09:04:00",
            "txn_type": "P2P",
            "channel": "PAYMENT_LINK",
            "city": "Noida",
            "device_id": "D2",
            "status": "SUCCESS",
            "note": "layering",
            "label": "fraud",
        },
        {
            "txn_id": "T4",
            "sender_id": "D",
            "receiver_id": "B",
            "amount": 7400,
            "txn_time": "2026-05-01T09:05:00",
            "txn_type": "P2P",
            "channel": "PAYMENT_LINK",
            "city": "Noida",
            "device_id": "D2",
            "status": "SUCCESS",
            "note": "layering",
            "label": "fraud",
        },
    ]

    engine = GraphRiskEngine(accounts, transactions)

    assert engine.score_account("B")["risk_score"] > engine.score_account("A")["risk_score"]
    assert engine.score_account("B")["risk_tier"] in {"High", "Critical"}
